version: '3.9'

services:
  backend:
    container_name: backend-container
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend-image
    restart: on-failure
    networks:
      - backend
    ports:
      - 4000:3000
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  frontend:
    container_name: frontend-container
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend-image
    restart: on-failure
    networks:
      - frontend
    ports:
      - 8081:80

  postgres:
    container_name: postgres-container
    image: postgres
    restart: on-failure
    networks:
      - backend
    volumes:
      - postgres_data:/data/postgres
    env_file:
      - ./backend/.env

  adminer:
    container_name: adminer-container
    image: adminer
    restart: on-failure
    networks:
      - backend
    ports:
      - 8082:8080
    depends_on:
      - postgres

networks:
  frontend:
  backend:

volumes:
  postgres_data: